### PR TITLE
Update Mergesort.py

### PR DESCRIPTION
**Pull request by zxr445116086**
There is something wrong with this code, when you run this code, it will say 'NameError: name 'A' is not defined'.
!!!!!!!!!! The parameters in other functions will also need to change!!!!!!
In order to fix this, I think you can add a parameter 'last', instead of setting 'last' as default, since that will cause the NameError.

### CODE REVIEW

**Comment by joeyajames** [comment]
zxr445116086, what version of Python are you using?

**Comment by zxr445116086** [comment]
JoeyaJames, Currently I'm using python 3.6.0, and I also tried the same code in python 2.7, and got the same result,   "NameError: name 'A' is not defined"

**Comment by joeyajames** [comment]
Okay, I tested it and got the same error as you. Thanks for your contribution, but I think when the user calls the mergesort function he should only need to pass 1 parameter, the list he wants to sort. So I uploaded a different fix to GitHub that I hope you'll like. --Joe

**Comment by zxr445116086** [comment]
Great! Add a function can solve this.
Thanks for your work and wonderful video explanation. It really helped me a lot!

**Pull request closed without merging**
